### ISSUE TITLE
Project directory overview?

### ISSUE THREAD

**Issue by mmealling** [FamilySearch/gedcomx-java#18]
I'm starting a Javascript implementation and I'm trying to understand what is core and what isn't. Specifically I'm looking at the gedcomx-rt-support, enunciate-gedcomx-support, and gedcomx-atom directories. Can I safely ignore them for now?

**Comment by stoicflame** [comment]
Hi.

> I'm starting a Javascript implementation

Cool!

> I'm looking at the gedcomx-rt-support, enunciate-gedcomx-support, and gedcomx-atom directories. Can I safely ignore them for now?

I think the *-support modules can be ignored for JavaScript.

The atom module is an implementation of the [GEDCOM X Atom Extensions](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/atom-model-specification.md), which are needed to fully support the [GEDCOM X RS Spec](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md). But I think you could get a long way down the road of implementation without having to cross the Atom bridge...
