### ISSUE TITLE
Create org.gedcomx.common.URI from a java.net.URI

### ISSUE THREAD

**Issue by rsbohn12** [FamilySearch/gedcomx-java#26]
Provide a way to create an org.gedcomx.common.URI from a java.net.URI. Otherwise I'm writing this nonsense:

    org.gedcomx.common.URI uri = new org.gedcomx.common.URI(ark.getURI().toString());

**Comment by stoicflame** [comment]
Agreed. We'll get this into the next release.

**Comment by stoicflame** [comment]
Fixed 8a960df at and available in version 1.0.139.M1.

Sorry that took as long as it did.
