### ISSUE TITLE
getSources() should be getSourceReferences()

### ISSUE THREAD

**Issue by BenjaminLimb** [FamilySearch/gedcomx-java#28]
The documentation reads:

Read Source References
```
//the person on which to read the source references.
PersonState person = ...;
//load the source references for the person.
person.loadSourceReferences();
//read the source references.
List<SourceReference> sourceRefs = person.getPerson().getSources();
```
However since getSources() returns a list of SourceReference it should be getSourceReferences()

**Comment by stoicflame** [comment]
The `sources` name is associated with the underlying data model. I.e. it looks like that in the XML:

```xml
<person>
  <source resource="...">
</person>
```

I guess it would have been better to name the java accessor `sourceReferences`, but at this point, I don't think it's worth the effort.
