### ISSUE TITLE
Which spec is SourceDescription.version a part of?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-java#46]

**Comment by stoicflame** [comment]
I actually don't know how that got there. It doesn't appear to be used by FamilySearch, so I can't identify a use case. It may just be a superfluous artifact of the Java code.

**Comment by justincy** [comment]
It appears to have been intentionally added a year ago in https://github.com/FamilySearch/gedcomx-java/commit/5f23fce3d3c13d2b64daa79cd950cd02bdecf70e. You can ask the committer about it, if you haven't already.

It appears in the source description that is attached to the GedcomX root element of a person response when requested from the platform API.

```js
  {
    "id" : "SD-K1VK-9B3",
    "citations" : [ {
      "lang" : "en",
      "value" : "\"Family Tree,\" database, <i>FamilySearch</i> (http://familysearch.org : modified 10 June 2016, 00:03), entry for Helen Gertrude Zierak(PID https://familysearch.org/ark:/61903/4:1:K1VK-9B3); contributed by various users."
    } ],
    "about" : "#K1VK-9B3",
    "componentOf" : {
      "description" : "https://familysearch.org/platform/collections/tree"
    },
    "titles" : [ {
      "value" : "Helen Gertrude Zierak"
    } ],
    "resourceType" : "http://gedcomx.org/Person",
    "identifiers" : {
      "http://gedcomx.org/Persistent" : [ "https://familysearch.org/ark:/61903/4:1:K1VK-9B3" ]
    },
    "modified" : 1465517011000,
    "version" : "136848098114480000"
  }
```

**Comment by stoicflame** [comment]
Okay, now I'm remembering.

Well, it needs to be at least added to the RS spec for now. We may want to consider moving it to the core spec.
