### ISSUE TITLE
SourceDescription.coverage should not be a list

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-java#47]
gedcomx-java has [SourceDescription.coverage](https://github.com/FamilySearch/gedcomx-java/blob/e13e14967c2ca4e76b1612327eaffdc1d6881eff/gedcomx-model/src/main/java/org/gedcomx/source/SourceDescription.java#L69) implemented as a list but the [Conceptual Model spec](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#source-description) and the [JSON Format spec](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#source-description) say that it's a single value.

**Comment by ranbo** [comment]
The spec should be updated. It turned out that in practice a list was often required, such as when a SourceDescription described a record collection that covered a couple of different date ranges and places.
