### ISSUE TITLE
SDK Sample App: Unable to authenticate client

### ISSUE THREAD

**Issue by shdblowers** [FamilySearch/gedcomx-java#53]
Hello, I am attempting to try out the SDK via the sample app [java-sdk-sample-app](https://github.com/FamilySearch/java-sdk-sample-app).

I have cloned the repo and am successfully running the App with maven like this:
```bash
mvn exec:java -Dexec.mainClass="org.familysearch.practice.App"
```
It prompts me for username / password / developer key, which I give and then I get this error: 
```java
org.gedcomx.rs.client.GedcomxApplicationException: Unable to obtain an access token ("invalid_grant": "Unable to authenticate client. [ clientId: MY_CLIENT_ID_WAS_HERE ].").
```

I have tried out the same details with the sample app here https://familysearch.org/developers/docs/sample-app and everything works, so I think something is wrong with the Java SDK sample app.

**Comment by justincy** [comment]
You need to send an email to devsupport@familysearch.org requesting that they enable the password grant type for your client ID.

**Comment by shdblowers** [comment]
Thanks for your response @justincy, I have sent an email as you suggested.
