### ISSUE TITLE
Simple build

### ISSUE THREAD

**Issue by AJAskey** [FamilySearch/gedcomx-java#74]
Doesn't build. Needs a bunch of libs not in the dependencies. You are not going to get much help on this if people cannot do a simple "mvn install" from the download. No one in universe has your dev setup on our computers.

From README.md:

git clone https://github.com/FamilySearch/gedcomx-java.git
cd gedcomx-java
mvn install

Dies almost immediately.
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/dev/gedcomx-java/gedcomx-rt-support/src/main/java/org/gedcomx/rt/GedcomNamespaceManager.java:[22,33] package javax.xml.bind.annotation does not exist

Sure, I added that dependency which leads to a Jackson error. Disappointing but I'll build my own.

**Comment by stoicflame** [comment]
🙂 Agreed.

The problem is just the Java version. This project is still on Java 8 and building with the latest Java version will fail because later versions decoupled those dependencies.

I'll get those dependencies declared.

**Comment by AJAskey** [comment]
Sorry for being bitchy. It is just almost every maven project I have tried to use in past year is a pain to setup. It is a systemic problem.

As I understand Maven, the POM can be setup to handle all of these issues. And if not the the Readme should define a clear dev environment.

I am really interested in your Gedcom work. I am creating my own as nothing out these is worth much today. This looked to be promising as it had been updated recently. My goal is to rebuild my tree from a US census perspective using my own parsing/processing of Gedcom and then rewriting the Gedcom.

**Comment by stoicflame** [comment]
Awesome. Well, we really want to support you in that effort, so I'll get the pom set up to handle cross-version build issues.

**Comment by AJAskey** [comment]
Thanks. I'll support you by testing your software and making suggestions.

**Comment by AJAskey** [comment]
Also having possibly same problem with **gedcom5-conversion** utility. I assume I need to use this to convert my GED file into a GEDX file.

**Comment by stoicflame** [comment]
Just wanted you to know that I haven't forgotten about this. I'm usually more responsive, but I've had to quarantine for a bit and have been away from my normal development environment.

**Comment by clarkegj** [comment]
No problem.  Have a fast recovery.

Gordon

**Comment by AJAskey** [comment]
Thanks. I have been out of touch recently myself.  Good luck to you.

Andy Askey


> Just wanted you to know that I haven't forgotten about this. I'm usually more responsive, but I've had to quarantine for a bit and have been away from my normal development environment.

**Comment by stoicflame** [comment]
I've pushed 78f2373c which updates the dependencies to support later Java versions.

**Comment by stoicflame** [comment]
I also pushed [7d4a8b3](https://github.com/FamilySearch/gedcom5-java/commit/7d4a8b3efbec70c2acb6c8bf5494511a4cec39e2) in `gedcom5-java` to support later Java versions.

**Comment by AJAskey** [comment]
mvn compile works for me.
mvn install generates this test error.
Maybe it is my environment.

[install.txt](https://github.com/FamilySearch/gedcomx-java/files/5603545/install.txt)

**Comment by stoicflame** [comment]
I'm not getting the same error. At 09876f3b I updated the hamcrest version, but I'd like to be able to replicate your env so I can ensure all the issues are addressed.

What's the output of `mvn -v`?

**Comment by stoicflame** [comment]
Re-opening so this thread doesn't get dropped.

Still looking for your output of `mvn -v` so I can make any needed adjustments.

**Comment by AJAskey** [comment]
Sorry. Too much going on during holidays.

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\dev\apache-maven-3.6.3
Java version: 15.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-15.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"**



> Re-opening so this thread doesn't get dropped.
> 
> Still looking for your output of `mvn -v` so I can make any needed adjustments.

**Comment by stoicflame** [comment]
Environment replicated and build confirmed.
