### ISSUE TITLE
Agent is missing optional "person" field.

### ISSUE THREAD

**Issue by jpvorenk** [FamilySearch/gedcomx-java#85]
The "person" field on Agent objects is defined [in the conceptual model](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#24-the-agent-data-type) and in the [json format specifications](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#24-the-agent-data-type) but is not included as a field on the [Agent class](https://github.com/FamilySearch/gedcomx-java/blob/master/gedcomx-model/src/main/java/org/gedcomx/agent/Agent.java#L51).

**Comment by stoicflame** [comment]
Available in version `2.145.0`.

**Comment by jpvorenk** [comment]
Thank you!
