### ISSUE TITLE
SourceDescription is missing optional "authors" field.

### ISSUE THREAD

**Issue by jpvorenk** [FamilySearch/gedcomx-java#86]
The "authors" field on SourceDescription objects is defined [in the conceptual model](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#23-the-sourcedescription-data-type) and in the [json format specifications](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#23-the-sourcedescription-data-type) but is not included as a field on the [SourceDescription class](https://github.com/FamilySearch/gedcomx-java/blob/master/gedcomx-model/src/main/java/org/gedcomx/source/SourceDescription.java#L68).

**Comment by stoicflame** [comment]
Available in version `2.145.0`.

**Comment by jpvorenk** [comment]
Thank you!
