### ISSUE TITLE
Add Branch to FactType

### ISSUE THREAD

**Issue by thnaeff** [FamilySearch/gedcomx-java#92]
Add 'Branch' to [FactType](https://github.com/FamilySearch/gedcomx-java/blob/b6496feff8f405176589493d9f339080d596b8ce/gedcomx-model/src/main/java/org/gedcomx/types/FactType.java), as specified here http://www.gedcomx.org/types/FactType.html and here https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md#21-person-fact-types

![image](https://user-images.githubusercontent.com/3227282/219903045-a87f8534-2fa1-4332-a181-c85436742c4f.png)

https://github.com/FamilySearch/gedcomx-java/blob/b6496feff8f405176589493d9f339080d596b8ce/gedcomx-model/src/main/java/org/gedcomx/types/FactType.java#L106

**Comment by stoicflame** [comment]
Thanks, we'll get it added.

**Comment by thnaeff** [comment]
> Thanks, we'll get it added.

Thanks for your quick reply. I figured why not just open a PR (see PR #93 ) - I appreciate all the work done here. I will be working with this here and there over the next year or so and would be happy to contribute where I can. If you have some formal contribution process documented, please let me know.

**Comment by stoicflame** [comment]
GH issues and PRs are great! Thanks for contributing!
